/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package rest

import (
	"encoding/json"
	"fmt"
	"net/http"
	"regexp"
	"strings"
	"time"

	"github.com/gorilla/mux"

	log "github.com/sirupsen/logrus"

	"github.com/mgrzybek/gonyxia-api/internal/core"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter(e *core.Engine) *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	engine = e
	return router
}

/*
 * TODO: deal with tracing
 * https://fernando-bandeira.medium.com/building-apis-with-go-part-3-instrumentation-and-error-handling-daba9385e3ec
 */
func Logger(inner http.Handler, name string) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()

		inner.ServeHTTP(w, r)

		log.WithFields(log.Fields{
			"method":               r.Method,
			"request":              r.RequestURI,
			"resource":             name,
			"process_time_seconds": time.Since(start),
		}).Info("access")
	})
}

func writeHttpResponse(w http.ResponseWriter, status int, message map[string]string) {
	w.WriteHeader(status)
	jmsg, _ := writeJsonResponse(message)
	fmt.Fprintf(w, "%s", jmsg)
}

func validateAuthorizationHeader(w http.ResponseWriter, r *http.Request) bool {
	message := make(map[string]string)
	message["message"] = "Given token is invalid."

	if len(r.Header.Get("Authorization")) < 7 {
		log.Warn(message["message"])
		writeHttpResponse(w, http.StatusUnauthorized, message)
		return false
	}

	log.Debug("Authorization header: " + r.Header.Get("Authorization"))
	matched, err := regexp.MatchString(`^Bearer [A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*$`, r.Header.Get("Authorization"))

	if err == nil && matched == true {
		log.Debug("Given token is valid")
		return true
	}

	log.Warn(message["message"] + " Header: " + r.Header["Authorization"][0])
	writeHttpResponse(w, http.StatusUnauthorized, message)
	return false
}

func writeJsonResponse(resp map[string]string) ([]byte, error) {
	j, err := json.Marshal(resp)
	if err != nil {
		log.Error("Error happened in JSON marshal. Err: %s", err)
	}
	return j, err
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var engine *core.Engine
var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"GetCloudShellStatus",
		strings.ToUpper("Get"),
		"/cloudshell",
		GetCloudShellStatus,
	},

	Route{
		"ApplyQuota",
		strings.ToUpper("Post"),
		"/my-lab/quota",
		ApplyQuota,
	},

	Route{
		"DestroyApp",
		strings.ToUpper("Delete"),
		"/my-lab/app",
		DestroyApp,
	},

	Route{
		"GetApp",
		strings.ToUpper("Get"),
		"/my-lab/app",
		GetApp,
	},

	Route{
		"GetLogs",
		strings.ToUpper("Get"),
		"/my-lab/app/logs",
		GetLogs,
	},

	Route{
		"GetMyServices",
		strings.ToUpper("Get"),
		"/my-lab/services",
		GetMyServices,
	},

	Route{
		"GetQuota",
		strings.ToUpper("Get"),
		"/my-lab/quota",
		GetQuota,
	},

	Route{
		"PublishService",
		strings.ToUpper("Put"),
		"/my-lab/app",
		PublishService,
	},

	Route{
		"ResetQuota",
		strings.ToUpper("Options"),
		"/my-lab/quota/reset",
		ResetQuota,
	},

	Route{
		"ResetQuota1",
		strings.ToUpper("Put"),
		"/my-lab/quota/reset",
		ResetQuota1,
	},

	Route{
		"ResetQuota2",
		strings.ToUpper("Post"),
		"/my-lab/quota/reset",
		ResetQuota2,
	},

	Route{
		"ResetQuota3",
		strings.ToUpper("Delete"),
		"/my-lab/quota/reset",
		ResetQuota3,
	},

	Route{
		"ResetQuota4",
		strings.ToUpper("Get"),
		"/my-lab/quota/reset",
		ResetQuota4,
	},

	Route{
		"ResetQuota5",
		strings.ToUpper("Head"),
		"/my-lab/quota/reset",
		ResetQuota5,
	},

	Route{
		"ResetQuota6",
		strings.ToUpper("Patch"),
		"/my-lab/quota/reset",
		ResetQuota6,
	},

	Route{
		"Onboard",
		strings.ToUpper("Post"),
		"/onboarding",
		Onboard,
	},

	Route{
		"Configuration",
		strings.ToUpper("Get"),
		"/public/configuration",
		Configuration,
	},

	Route{
		"GetCatalogById",
		strings.ToUpper("Get"),
		"/public/catalog/{catalogId}",
		GetCatalogById,
	},

	Route{
		"GetCatalogs",
		strings.ToUpper("Get"),
		"/public/catalog",
		GetCatalogs,
	},

	Route{
		"GetIP",
		strings.ToUpper("Get"),
		"/public/ip",
		GetIP,
	},

	Route{
		"GetPackage",
		strings.ToUpper("Get"),
		"/public/catalog/{catalogId}/{packageName}",
		GetPackage,
	},

	Route{
		"GetRegions",
		strings.ToUpper("Get"),
		"/public/regions",
		GetRegions,
	},

	Route{
		"Healthcheck",
		strings.ToUpper("Get"),
		"/public/healthcheck",
		Healthcheck,
	},

	Route{
		"UserInfo",
		strings.ToUpper("Get"),
		"/user/info",
		UserInfo,
	},
}
