/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core

type Group struct {
	Id string `json:"id,omitempty"`

	Apps []Service `json:"apps,omitempty"`
}
