/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core

type XGenerated struct {
	Type_ string `json:"type,omitempty"`

	Scope string `json:"scope,omitempty"`

	Name string `json:"name,omitempty"`
}
