/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core

type UninstallService struct {
	Path string `json:"path,omitempty"`

	Success bool `json:"success,omitempty"`
}
