/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core

type AppInfo struct {
	Build *BuildInfo `json:"build,omitempty"`

	Regions []Region `json:"regions,omitempty"`
}
