/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core

type Project struct {
	Id string `json:"id,omitempty"`

	Group string `json:"group,omitempty"`

	Bucket string `json:"bucket,omitempty"`

	Namespace string `json:"namespace,omitempty"`

	Name string `json:"name,omitempty"`
}
