/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core

type CloudshellConfiguration struct {
	CatalogId string `json:"catalogId,omitempty"`

	PackageName string `json:"packageName,omitempty"`
}
