/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core

type DefaultConfiguration struct {
	NetworkPolicy bool `json:"networkPolicy,omitempty"`

	Ipprotection bool `json:"ipprotection,omitempty"`
}
