/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core

type Config struct {
	Type_ string `json:"type,omitempty"`

	Properties *Category `json:"properties,omitempty"`

	Required []string `json:"required,omitempty"`
}
