/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core
/*
type Catalogs struct {
	Catalogs []CatalogWrapper `json:"catalogs,omitempty"`
}
*/