/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core

import (
)

type Services struct {
	Server *Server `json:"server"`

	Driver *OrchestratorAdapter

	Type_ string `json:"type,omitempty"`

	SingleNamespace bool `json:"singleNamespace,omitempty"`

	NamespacePrefix string `json:"namespacePrefix,omitempty"`

	GroupNamespacePrefix string `json:"groupNamespacePrefix,omitempty"`

	UsernamePrefix string `json:"usernamePrefix,omitempty"`

	GroupPrefix string `json:"groupPrefix,omitempty"`

	AuthenticationMode string `json:"authenticationMode,omitempty"`

	Expose *Expose `json:"expose,omitempty"`

	Monitoring *Monitoring `json:"monitoring,omitempty"`

	Cloudshell *CloudshellConfiguration `json:"cloudshell,omitempty"`

	InitScript string `json:"initScript,omitempty"`

	Quotas *Quotas `json:"quotas,omitempty"`

	DefaultConfiguration *DefaultConfiguration `json:"defaultConfiguration,omitempty"`
}

// if Services.server is nil then in-cluster mode
/*
func (c *Services) Ping() error {

}
*/
