/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core

type TaskStatus struct {
	Status string `json:"status,omitempty"`

	Reason string `json:"reason,omitempty"`
}
