/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core

type Hidden struct {
	Value *interface{} `json:"value,omitempty"`

	Path string `json:"path,omitempty"`
}
