/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core

type Quotas struct {
	Enabled bool `json:"enabled,omitempty"`

	AllowUserModification bool `json:"allowUserModification,omitempty"`

	Default_ *Quota `json:"default,omitempty"`
}
