/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core

type S3 struct {
	Monitoring *Monitoring `json:"monitoring,omitempty"`

	URL string `json:"URL,omitempty"`
}
