/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core

type Container struct {
	Name string `json:"name,omitempty"`

	Ready bool `json:"ready,omitempty"`
}
