/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core

type BuildInfo struct {
	Version string `json:"version,omitempty"`

	Timestamp int64 `json:"timestamp,omitempty"`
}
