/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core

type CloudShellStatus struct {
	Status string `json:"status,omitempty"`

	Url string `json:"url,omitempty"`

	PackageToDeploy *Pkg `json:"packageToDeploy,omitempty"`

	CatalogId string `json:"catalogId,omitempty"`
}
