/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core

type Task struct {
	Id string `json:"id,omitempty"`

	Status *TaskStatus `json:"status,omitempty"`

	Containers []Container `json:"containers,omitempty"`
}
