/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core

type XForm struct {
	Hidden bool `json:"hidden,omitempty"`

	Readonly bool `json:"readonly,omitempty"`

	Value string `json:"value,omitempty"`
}
