/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core

type Pkg struct {
	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	Version string `json:"version,omitempty"`

	Config *Config `json:"config,omitempty"`
}
