/*
 * Onyxia-api
 *
 * Swagger onyxia-api
 *
 * API version: snapshot
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package core

type Location struct {
	Lat float64 `json:"lat,omitempty"`

	Name string `json:"name,omitempty"`

	Long float64 `json:"long,omitempty"`
}
