name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      
    - name: Install dependencies
      run: make get
      
    - name: Run check
      run: make test
      
    - name: Run onyxia-api
      run: make onyxia-api

